import React, { useEffect, useState } from "react";
import { useRef } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import FacebookIcon from "@mui/icons-material/Facebook";
import LinkedInIcon from "@mui/icons-material/LinkedIn";
import TwitterIcon from "@mui/icons-material/Twitter";
import InstagramIcon from "@mui/icons-material/Instagram";

export default function Home() {
  const [text, setText] = useState("");
  const introText = "Welcome To Code with COD";
  const typingForward = useRef(true);

  useEffect(() => {
    let currentIndex = 0;

    const typingInterval = setInterval(() => {
      if (typingForward.current) {
        if (currentIndex <= introText.length) {
          setText(introText.slice(0, currentIndex));
          currentIndex++;
        } else {
          typingForward.current = false;
          currentIndex = introText.length;
        }
      } else {
        if (currentIndex >= 0) {
          setText(introText.slice(0, currentIndex));
          currentIndex--;
        } else {
          typingForward.current = true;
          currentIndex = 0;
        }
      }
    }, 100);

    return () => {
      clearInterval(typingInterval);
    };
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/codLogo.jpg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navBarContainer}>
          <h1>{text}</h1>
          <div className={styles.navBarIcons}>
            <h1>
              <FacebookIcon />
            </h1>
            <h1>
              <LinkedInIcon />
            </h1>
            <h1>
              <TwitterIcon />
            </h1>
            <h1>
              <InstagramIcon />
            </h1>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/codLogo.jpg"
            alt="Next.js Logo"
            width={500}
            height={400}
          />
        </div>

        <div className={styles.grid}>
          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span></span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
